### ISSUE TITLE
Array.prototype.find() and Array.prototype.findIndex() issues

### ISSUE THREAD

**Issue by sainaen** [apigee/rhino#24]
Hi,

I'm working on adding support for arrow functions (actually it's overstatement, I'm just polishing implementation done by @tuchida in this [mozilla/rhino PR](https://github.com/mozilla/rhino/pull/120)) and I've found two problems with 'find()' and 'findIndex()' that were added recently.

**First**, for code
```js
[1,2,3].find(i => i % 2 == 0)
```
Rhino will throw rather funny exception
```
js: uncaught JavaScript runtime exception: TypeError: org.mozilla.javascript.ArrowFunction@34fe7e0e is not a function, it is function
```
because [it expects](https://github.com/apigee/rhino/blob/master/src/org/mozilla/javascript/NativeArray.java#L1602) to get only instances of `NativeFunction` as a callback (this check is done only for `find()` and `findIndex()`), and here I'm passing an instance of `ArrowFunction`. 

**Second**, for code
```js
var a = [1,2,3];
a.find(function (i) { return i % 2 == 0; }, a);
```
Rhino will throw
```
js: uncaught JavaScript runtime exception: TypeError: Array.prototype method called on null or undefined
```
because again [it expects](https://github.com/apigee/rhino/blob/master/src/org/mozilla/javascript/NativeArray.java#L1615) that for `find()` or `findIndex()` second argument (`thisArg`) should never be the same as array itself on which these methods were invoked.

I suppose, both are just mechanical errors, but they were commited with message "more V8 compatibility" and I want to be sure that I'm not breaking anything removing those checks.

//cc @eshepelyuk

**Comment by gbrail** [comment]
Evgeny put in those changes in order to maintain compatibility with V8 for the new features, but without breaking backward compatibility for existing Rhino users of other functions, so he's probably the best one to address your issue.

**Comment by eshepelyuk** [comment]
I propose to change conditions, instead analyzing method names rely on `RHINO` version flag, that will be introduced in #26
